=== benlhachemi/e-polytechnique/xml/dtd/livre.dtd
<!ELEMENT Livre (Sections,Auteurs)>
<!ELEMENT Sections (Section+)>
<!ELEMENT Section (titre,Chapitre+)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT Chapitre (titre,p+)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT Auteurs (Auteur+)>
<!ELEMENT Auteur (Nom,Prenom)>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>

=== benlhachemi/e-polytechnique/xml/livre.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Livre SYSTEM "./dtd/livre.dtd">
<Livre>
    <Sections>
        <Section>
            <titre>titre de la section</titre>
            <Chapitre>
                <titre>Titre du chapitre</titre>
                <p>Lorem Ipsum is simply dummy text of the</p>
                <p>Lorem Ipsum is simply dummy text of the</p>
            </Chapitre>
            <Chapitre>
                <titre>Titre du chapitre</titre>
                <p>Lorem Ipsum is simply dummy text of the</p>
                <p>Lorem Ipsum is simply dummy text of the</p>
            </Chapitre>
        </Section>
        <Section>
            <titre>titre de la section</titre>
            <Chapitre>
                <titre>titre de la section</titre>
                <p>Lorem Ipsum is simply dummy text of the</p>
                <p>Lorem Ipsum is simply dummy text of the</p>
            </Chapitre>
            <Chapitre>
                <titre>titre de la section</titre>
                <p>Lorem Ipsum is simply dummy text of the</p>
                <p>Lorem Ipsum is simply dummy text of the</p>
            </Chapitre>
        </Section>
    </Sections>
    <Auteurs>
        <Auteur>
            <Nom>Benlhachemi</Nom>
            <Prenom>Souhail</Prenom>
        </Auteur>
        <Auteur>
            <Nom>Benlhachemi</Nom>
            <Prenom>Souhail</Prenom>
        </Auteur>
    </Auteurs>
</Livre>
